apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flyem
  name: flyem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flyem
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flyem
    spec:
      containers:
      - image: asimyildiz/flyem:latest
        name: flyem
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flyem
  name: flyem
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: flyem
  type: ClusterIP
status:
  loadBalancer: {}
