apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: fares
  name: fares
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fares
  strategy: {}
  template:
    metadata:      
      labels:
        app: fares
    spec:
      containers:
      - image: asimyildiz/flyem:service-fares-0.0.3-SNAPSHOT
        name: flyem
        ports:
        - containerPort: 8080
        - containerPort: 9090        
        imagePullPolicy: Always
        env:
        - name: spring.profiles.active
          value: 'prod'        
        resources: {}        
status: {}
---
apiVersion: v1
kind: Service
metadata:  
  labels:
    app: fares-svc
  name: fares-svc
spec:
  selector:
    app: fares
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090  
  type: ClusterIP
status:
  loadBalancer: {}
